services:
  - type: web
    name: stock-dashboard
    runtime: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app.server --workers 1 --threads 1 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FINLAB_TOKEN
        fromSecret: FINLAB_TOKEN
      - key: API_KEY
        fromSecret: API_KEY
      - key: SECRET_KEY
        fromSecret: SECRET_KEY